### PR TITLE
Create DNA Analysis

### PR DESCRIPTION
**Pull request by lncxd**
For the Gene analyzing part of the tool.

### CODE REVIEW

**Comment by lncxd** [comment]
Updates to DNA Analysis

**Comment by lncxd** [comment]
Protein Analysis file

**Comment by lncxd** [comment]
Did you receive the new update pull request? I'm new to this so I'm not sure if I did it right. I moved all the analysis files to the genetics folder on my forked version and then I _think_ I made a pull request.

**Comment by sdhutchins** [comment]
@lncxd As long as you made changes to the current branch that is open with this PR, it will update, and it has.

**Comment by lncxd** [comment]
Excellent.

**Comment by lncxd** [comment]
Sounds good. Thanks for telling me.

**Comment by sdhutchins** [comment]
@lncxd Also, check my edits [here](https://github.com/sdhutchins/labrat/tree/master/labrat/genetics)

**Pull request merged**
